#!/bin/bash

echo "🚀 Setting up new repository for Enhanced Game Hub"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to GitHub and create a new repository"
echo "   - Repository name: enhanced-game-hub (or your preferred name)"
echo "   - Description: Enhanced gaming hub with Bubble Pop, Casino Slots, and Fruit Swipe games"
echo "   - Make it Public or Private (your choice)"
echo "   - DO NOT initialize with README, .gitignore, or license"
echo ""
echo "2. After creating the repo, copy the repository URL and run:"
echo "   git remote add new-origin YOUR_REPO_URL"
echo "   git push -u new-origin main"
echo ""
echo "3. Your enhanced games will be available at the new repository!"
echo ""
echo "📁 Current project structure:"
ls -la | grep -E "^d|package.json|README.md|src"
echo ""
echo "🎮 Enhanced features included:"
echo "   ✅ Bubble Pop Game with sound effects and animations"
echo "   ✅ Casino Slot Machine with win celebrations"
echo "   ✅ Fruit Swipe Game (Candy Crush style)"
echo "   ✅ Responsive design for mobile and desktop"
echo "   ✅ Mute/unmute functionality"
echo "   ✅ Enhanced visual effects and transitions"